[features]
seeds = false
skip-lint = false

[programs.localnet]
the_community_atlas = "EvWszVN16HcjNaZnkvFb54WsQTiF65rMzrqPfekRR583"

[programs.devnet]
the_community_atlas = "EvWszVN16HcjNaZnkvFb54WsQTiF65rMzrqPfekRR583"

[programs.mainnet]
the_community_atlas = "EvWszVN16HcjNaZnkvFb54WsQTiF65rMzrqPfekRR583"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
